name: OZIP Decrypter by TechyMinati... 

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

env:
  FIRMWARE_LINK: https://assorted.downloads.oppo.com/firmware/CPH2095/CPH2095PU_11_OTA_0290_all_UJNxBjvpsQSr.ozip #edit link here...
  FIRMWARE_NAME: CPH2095PU_11_OTA_0290_all_UJNxBjvpsQSr.ozip #edit file name here, you can find the name of file from link itself...
  FINAL_ZIP_NAME: THE_NAME_OF_ZIP_YOU_WANT.zip #This will be the name of final zip which will be uploaded. You can leave it unchanged.
  TZ: Asia/Tongi

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
         
       - name: Downloading Ozip Now
         run: |
            sudo -E apt-get -qq update
            sudo apt install aria2
            aria2c $FIRMWARE_LINK
             
       - name: Decrypting Ozip Now
         run: |
             sudo -E apt-get -qq update
             sudo apt-get install python-pip
             sudo -H pip install --upgrade pip
             sudo -H pip install setuptools wheel docopt pycryptodome
             wget https://raw.githubusercontent.com/techyminati/oppo_ozip_decrypt/master/ozipdecrypt.py
             sudo python ozipdecrypt.py $FIRMWARE_NAME             

       - name: Upload Decrypted zip if AES keys not found.
         continue-on-error: true
         run: |
             curl --upload-file ./ *.zip https://transfer.sh/*.zip #file will be uploaded to bashupload, so mirror it if you are decrypting for community uses


       - name: ziping decrypted file if needed.
         continue-on-error: true
         run: |
             cd out
             sudo zip -r $FINAL_ZIP_NAME * #Don't edit it. Don't edit it and Don't edit this line.


       - name: Upload Decrypted zip if AES keys not found.
         continue-on-error: true
         run: |
             echo "If you can't find your zip here, check the above ***UPLOAD*** section."
             cd out
             curl --upload-file ./ $FINAL_ZIP_NAME https://transfer.sh/$FINAL_ZIP_NAME #file will be uploaded to bashupload, so mirror it if you are decrypting for community uses.
